{
  imports = [
    ./chatterino7.nix
    ./discord.nix
    ./flatpak.nix
    ./fooyin.nix
    ./google-chrome.nix
    ./kde.nix
    ./libreoffice.nix
    ./mangohud.nix
    ./mpv.nix
    ./obs.nix
    ./obsidian.nix
    ./osu-lazer.nix
    ./polychromatic.nix
    ./prismlauncher.nix
    ./reaper.nix
    ./spotify.nix
    ./vlc.nix
  ];
}
